### ISSUE TITLE
The query URL is not working anymore

### ISSUE THREAD

**Issue by bandi88** [mivk/ip-country#1]
Please check the script and update it. Because the query URL "https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix;resource=" is not anymore valid. 

By using this, error orccurs with output like (see [example](https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix;resource=de)): 

```
{
    "messages": [
        [
            "error",
            "The parameter 'resource' is required."
        ]
    ],
    "see_also": [],
    "version": "0.2",
    "data_call_status": "supported - connecting to ursa",
    "cached": false,
    "data": {},
    "query_id": "20210529143649-ef273634-f8f0-4d1f-92ff-6612d498e767",
    "process_time": 11,
    "server_id": "app138",
    "build_version": "live.2021.5.21.165",
    "status": "error",
    "status_code": 400,
    "time": "2021-05-29T14:36:49.366745"
}
```

**Comment by bandi88** [comment]
The token character in the query URL can be changed to
https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix**&**resource=de

So, the query should work.
Please do some tests to prove that it works, and then do change the script accordingly.

**Comment by bandi88** [comment]
The token character in the query URL can be changed to (by replacing the ';' by '&'): 

`https://stat.ripe.net/data/country-resource-list/data.json?v4_format=prefix&resource=de`

So, the query should work.
Please do some tests to prove that it works, and then do change the script accordingly.

**Comment by mivk** [comment]
Thanks to both of you. I had forgotten to also fix it here.
